
from typing import TypedDict

# This is our 'clipboard' that gets passed between our AI agents
class AgentState(TypedDict):
    question: str           # The user's original question
    schema_context: str     # NEW: The table information pulled from ChromaDB
    sql_query: str          # The SQL query generated by the AI
    sql_valid: bool         # A true/false check if the SQL is safe to run
    data_result: str        # The raw data returned from the database
    final_answer: str       # The final plain-English summary for the user
import os
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, END

# 1. Load secrets and connect to Database & AI
load_dotenv()
db = SQLDatabase.from_uri("sqlite:///data/AdventureWorks.db")
llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)



import chromadb

# Connect to ChromaDB
chroma_client = chromadb.PersistentClient(path="data/chroma_db")
schema_collection = chroma_client.get_collection(name="adventureworks_schema")

# --- WORKER 0: SCHEMA RETRIEVER ---
def retrieve_schema(state: AgentState):
    print("-> Worker 0: Retrieving relevant schema from memory...")
    question = state["question"]
    
    # Search ChromaDB for the 2 most relevant tables based on the question
    results = schema_collection.query(
        query_texts=[question],
        n_results=2
    )
    
    # Format the results into a readable string
    retrieved_tables = ""
    for i in range(len(results['documents'][0])):
        table_name = results['metadatas'][0][i]['table_name']
        description = results['documents'][0][i]
        retrieved_tables += f"Table '{table_name}': {description}\n"
        
    print(f"   [+] Retrieved Tables:\n{retrieved_tables.strip()}")
    
    # Return the context to the clipboard
    return {"schema_context": retrieved_tables.strip()}



# --- WORKER 1: SQL GENERATOR ---
def generate_sql(state: AgentState):
    print("-> Worker 1: Generating SQL...")
    question = state["question"]
    schema = state.get("schema_context", "") # Get the schema from the clipboard
    
    # We ask Gemini to translate the question into SQL USING the provided schema
    prompt = f"""You are a SQLite expert. 
    Write a SQL query to answer this question: {question}
    
    Use the following table schemas to help you write the query:
    {schema}
    
    Only return the SQL query, nothing else. No markdown formatting like ```sql.
    """
    
    response = llm.invoke(prompt)
    
    if isinstance(response.content, list):
        raw_text = response.content[0].get("text", "")
    else:
        raw_text = response.content
        
    sql = raw_text.replace('```sql', '').replace('```', '').strip()
    return {"sql_query": sql}

# --- WORKER 2: THE EXECUTOR ---
def execute_sql(state: AgentState):
    print("-> Worker 2: Executing SQL against database...")
    query = state["sql_query"]
    
    try:
        # Run the SQL query against AdventureWorks
        result = db.run(query)
    except Exception as e:
        result = f"Error: {e}"
        
    # Return the raw data to the clipboard
    return {"data_result": str(result)}

# --- WORKER 3: THE VALIDATOR ---
def validate_sql(state: AgentState):
    print("-> Worker 3: Validating SQL for safety...")
    query = state.get("sql_query", "")
    
    # Simple security check: Only allow SELECT statements
    if query.strip().upper().startswith("SELECT"):
        print("   [+] Query is safe (SELECT only).")
        return {"sql_valid": True}
    else:
        print("   [!] SECURITY ALERT: Blocked dangerous or invalid query!")
        return {"sql_valid": False}

# --- ROUTER: DECIDE NEXT STEP ---
def route_validation(state: AgentState):
    # If the SQL is valid, go to the executor. If not, stop the process.
    if state.get("sql_valid") == True:
        return "executor"
    else:
        return END


# --- WORKER 4: INSIGHT GENERATOR ---
def generate_insight(state: AgentState):
    print("-> Worker 4: Generating human-readable insight...")
    question = state["question"]
    sql = state.get("sql_query", "")
    data = state.get("data_result", "No data returned")
    
    # We ask Gemini to summarize the raw data into a friendly answer
    prompt = f"""You are a helpful Enterprise Data Analyst. 
    The user asked: {question}
    The SQL query executed was: {sql}
    The raw database result is: {data}
    
    Based on this result, write a short, professional answer to the user's question. 
    Do not mention the SQL query in your response, just answer the question.
    """
    
    response = llm.invoke(prompt)
    
    # Safely extract the text
    if isinstance(response.content, list):
        insight = response.content[0].get("text", "")
    else:
        insight = response.content
        
    # Paste the final human-readable answer to the clipboard
    return {"final_answer": insight.strip()}

# --- BUILD THE FLOWCHART ---
workflow = StateGraph(AgentState)

# 1. Add all workers to the graph
workflow.add_node("schema_retriever", retrieve_schema)
workflow.add_node("sql_generator", generate_sql)
workflow.add_node("validator", validate_sql)
workflow.add_node("executor", execute_sql)
workflow.add_node("insight_generator", generate_insight)

# 2. Define the exact order of operations
workflow.set_entry_point("schema_retriever") # We now start here!
workflow.add_edge("schema_retriever", "sql_generator")
workflow.add_edge("sql_generator", "validator") 

workflow.add_conditional_edges(
    "validator", 
    route_validation
)

workflow.add_edge("executor", "insight_generator") 
workflow.add_edge("insight_generator", END) 

app = workflow.compile()

# --- TEST IT! ---

if __name__ == "__main__":
    print("\n--- Starting the LangGraph AI Team ---")
    
    initial_clipboard = {"question": "What are the names and list prices of all products?"}    
    final_state = app.invoke(initial_clipboard)
    
    print("\n--- Final Clipboard Results ---")
    print(f"Generated SQL: {final_state.get('sql_query')}")
    print(f"Raw Database Output: {final_state.get('data_result')}")
    print(f"\nAI Analyst Response: {final_state.get('final_answer')}")